# This is a basic workflow to help you get started with Actions

name: TF2Build

on:
  push:
    branches: [ master ]
    paths-ignore: 'README.md'

jobs:
  build:
    runs-on: windows-2019

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Dependencies
      run: |
#pacman -S git patch unzip

#pip3 install six numpy wheel
#pip3 install keras_applications==1.0.6 --no-deps
#pip3 install keras_preprocessing==1.0.5 --no-deps

    - name: Setup
      run: |
        git clone --branch v2.2.0 https://github.com/tensorflow/tensorflow.git

    - name: Configure
      run: |
        cd ./tensorflow
        python ./configure.py
        
    - name: Build
      run: |
        bazel build //tensorflow/tools/lib_package:libtensorflow
